### PR TITLE
CFTP for GAMP3/4/5 improvements

### PR DESCRIPTION
**Pull request by metmajer**
Solves #67.

### CODE REVIEW

**Comment by metmajer** [comment]
[EDP-CFTP-SuggestedChanges-v0.1.pdf](https://github.com/opendevstack/ods-document-generation-templates/files/7913679/EDP-CFTP-SuggestedChanges-v0.1.pdf)

**Comment by metmajer** [comment]
[EDP-CFTP-SuggestedChanges-v0.2.pdf](https://github.com/opendevstack/ods-document-generation-templates/files/7963287/EDP-CFTP-SuggestedChanges-v0.2.pdf)

**Comment by metmajer** [comment]
[EDP-CFTP-SuggestedChanges-v0.3.pdf](https://github.com/opendevstack/ods-document-generation-templates/files/7986257/EDP-CFTP-SuggestedChanges-v0.3.pdf)

**Comment by metmajer** [comment]
[EDP-CFTP-SuggestedChanges-v1.0.pdf](https://github.com/opendevstack/ods-document-generation-templates/files/8010823/EDP-CFTP-SuggestedChanges-v1.0.pdf)

**Comment by metmajer** [comment]
@clemensutschig content fully approved by med QA, biz QA pending

**Comment by metmajer** [comment]
Fully approved after some minor polishing @clemensutschig @s2oBCN

**Review by s2oBCN — APPROVED** [review]

**Comment by clemensutschig** [comment]
Super!!!

**Pull request merged**
