### PR TITLE
Updated section 12 in SSDS-5 to remove SonarQube references

### PR DESCRIPTION
**Pull request by hrcornejo**

### CODE REVIEW

**Review by metmajer — CHANGES_REQUESTED** [review]
Thanks @hrcornejo, but we need to fill in something here. I will prepare a sentence.

**Comment by hrcornejo** [comment]
Ok @metmajer when you have the sentence I'll update all SSDS-x templates. Because all have the N/A now

**Comment by metmajer** [comment]
@hrcornejo @s2oBCN here is the approved sentence to be used in section 12.

> Detailed results of the coding review can be seen within the individual approved and merged Bitbucket Pull Requests in section 2.3.

**Comment by metmajer** [comment]
@hrcornejo are you sure that this needs to be entered into all documents? A GAMP 3 category document should not contain code review data since there is no code. Please only change where the rest of the document also contained code review information. I assume this is only for GAMP 5.

**Comment by hrcornejo** [comment]
@metmajer modified, only in 5 now

**Review by metmajer — APPROVED** [review]
Looks good @hrcornejo! 👍

**Comment by hrcornejo** [comment]
Merged in master and 4.x @metmajer

**Pull request merged**
