### PR TITLE
Fix missed rows in IVP template

### PR DESCRIPTION
**Pull request by jorge-romero**
In the IVP template, there were two row missing in the conclussion table, with this fix we add the missing information as exists in the word template of the document

### CODE REVIEW

**Review by metmajer — APPROVED** [review]

**Review by metmajer — CHANGES_REQUESTED** [review]
@jorge-romero Note sure about this one?

> Enter additional information, if necessary:

**Comment by jorge-romero** [comment]
> @jorge-romero Note sure about this one?
> 
> > Enter additional information, if necessary:

I'll ask for confirmation regarding that last sentence. It appear in the word template in that way but let me confirm that.

**Comment by metmajer** [comment]
@jorge-romero I figured it was in the Word template ;-) But our automated service won't allow such additional information to be entered.

**Comment by jorge-romero** [comment]
@metmajer After checking with the right people and have their approval on the generated pdf, the table have been removed from the template and a subsituted by a message that indicates where to find the conclusions.

**Review by metmajer — APPROVED** [review]

**Comment by metmajer** [comment]
@jorge-romero great :) we also need this in 4.x, don't forget.

**Review by metmajer — APPROVED** [review]

**Pull request merged**
