### PR TITLE
Remove .idea directory

### PR DESCRIPTION
**Pull request by jafarre-viewnext**

### CODE REVIEW

**Review by michaelsauter — APPROVED** [review]

**Review by michaelsauter — COMMENTED** [review]
Actually, you'd probably want to add it to `.gitginore` now?

**Comment by michaelsauter** [comment]
Forget my comment. Saw #46 now.

**Comment by metmajer** [comment]
@jafarre-viewnext please merge soon

**Comment by jafarre-viewnext** [comment]
@metmajer I don't seem to have write access to this master branch and I can't merge the pull request.

**Pull request merged**
